[tool.black]
line-length = 100

[tool.coverage.report]
exclude_lines = [
  "pragma: nocover",
  "raise NotImplementedError",
  "if TYPE_CHECKING:",
]

[tool.nbqa.mutate]
isort = 1
black = 1
pyupgrade = 1
