name: pymc3-dev-py37
channels:
- conda-forge
- defaults
dependencies:
- h5py>=2.7
- ipython>=7.16
- libblas=*=*mkl
- mkl-service
- nbsphinx>=0.4
- numpy=1.15
- numpydoc>=0.9
- pandas=0.24
- pre-commit>=2.8.0
- pytest-cov>=2.5
- pytest>=3.0
- python-graphviz
- python=3.7
- recommonmark>=0.4
- scipy=1.2
- sphinx-autobuild>=0.7
- sphinx>=1.5
- watermark
